# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35ed8b40adef63eff7b8094d3aa0c5775d799062842bb1f63d193b918fd4fa99c5a6c436c8afc5f2a8ff348cd5382fa40c5c1c4028a1dd496bd1f052e4fce7f6

test:
  secret_key_base: b32adadf2f1d10490200682815c73f0ae930bb49d24568c4aca3c8f1a1184c29792a161af5095849d69d306249b2b1fc9b5dba3ca20d07f87bab663f05a0e523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
